FROM apache/hive:3.1.3

COPY mysql-connector-java-5.1.49.jar /opt/hive/lib/
COPY hive-config/hive-site.xml /opt/hive/conf/

ENV HADOOP_USER_NAME=root \
    HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop \
    HIVE_CONF_DIR=/opt/hive/conf \
    HIVE_LOG_DIR=/opt/hive/logs

RUN mkdir -p /opt/hive/scratch /opt/hive/resources /opt/hive/logs

COPY entrypoint.sh /opt/hive/bin/
RUN chmod +x /opt/hive/bin/entrypoint.sh

ENTRYPOINT ["/opt/hive/bin/entrypoint.sh"] 