services:
  namenode:
    image: apache/hadoop:3
    hostname: namenode
    container_name: namenode
    command: bash -c "hdfs namenode -format && hdfs namenode"
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./hadoop_data/namenode:/hadoop/dfs/name
      - ./config:/opt/hadoop/etc/hadoop
    environment:
      - HADOOP_USER_NAME=root
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    user: "0"
      
  datanode1:
    image: apache/hadoop:3
    hostname: datanode1
    container_name: datanode1
    command: ["hdfs", "datanode"]
    volumes:
      - ./hadoop_data/datanode:/hadoop/dfs/data
      - ./config:/opt/hadoop/etc/hadoop
    environment:
      - HADOOP_USER_NAME=root
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    user: "0"
    depends_on:
      - namenode

  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    container_name: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - "8088:8088"
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
    depends_on:
      - namenode
      - datanode1

  nodemanager:
    image: apache/hadoop:3
    hostname: nodemanager
    container_name: nodemanager
    command: ["yarn", "nodemanager"]
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
    depends_on:
      - namenode
      - datanode1
      - resourcemanager

  spark-master:
    image: apache/spark:3.5.1
    hostname: spark-master
    container_name: spark-master
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - ./spark_data/logs:/opt/spark/logs
    environment:
      - SPARK_NO_DAEMONIZE=true
      - HADOOP_USER_NAME=root
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    depends_on:
      - namenode
      - resourcemanager

  spark-worker:
    image: apache/spark:3.5.1
    hostname: spark-worker
    container_name: spark-worker
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    ports:
      - "8081:8081"
    volumes:
      - ./config:/opt/hadoop/etc/hadoop
      - ./spark_data/logs:/opt/spark/logs
      - ./spark_data/work:/opt/spark/work
    environment:
      - SPARK_NO_DAEMONIZE=true
      - HADOOP_USER_NAME=root
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master

volumes:
  hadoop_namenode:
  hadoop_datanode:
